<?php
declare(strict_types=1);

namespace App\Core;

/**
 * Minimal .env reader. No Composer, no external dependency — the file is read
 * once at boot and the values are cached in a static array.
 */
final class Env
{
    private static array $values = [];
    private static bool $loaded = false;

    public static function load(string $path): void
    {
        self::$loaded = true;

        if (!is_readable($path)) {
            return;
        }

        $lines = file($path, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES) ?: [];

        foreach ($lines as $line) {
            $line = trim($line);

            if ($line === '' || str_starts_with($line, '#') || !str_contains($line, '=')) {
                continue;
            }

            [$key, $value] = explode('=', $line, 2);
            $key   = trim($key);
            $value = trim($value);

            // Strip an inline comment, but only when the value is unquoted.
            if ($value !== '' && $value[0] !== '"' && $value[0] !== "'" && str_contains($value, ' #')) {
                $value = substr($value, 0, (int) strpos($value, ' #'));
            }

            $value = trim($value);
            $len   = strlen($value);

            if ($len >= 2 && (($value[0] === '"' && $value[$len - 1] === '"') || ($value[0] === "'" && $value[$len - 1] === "'"))) {
                $value = substr($value, 1, -1);
            }

            self::$values[$key] = $value;
        }
    }

    public static function get(string $key, mixed $default = null): mixed
    {
        if (!self::$loaded) {
            return $default;
        }

        $value = self::$values[$key] ?? null;

        if ($value === null || $value === '') {
            return $default;
        }

        return match (strtolower($value)) {
            'true', '(true)'   => true,
            'false', '(false)' => false,
            'null', '(null)'   => null,
            default            => $value,
        };
    }

    public static function all(): array
    {
        return self::$values;
    }

    /** Write an .env file from an associative array (used by the installer). */
    public static function write(string $path, array $values): bool
    {
        $out = "# Generated by the SARCNA 2027 installer on " . date('Y-m-d H:i:s') . "\n";
        $out .= "# Do not commit this file to version control.\n\n";

        foreach ($values as $key => $value) {
            if (is_bool($value)) {
                $value = $value ? 'true' : 'false';
            }
            $value = (string) $value;
            if ($value === '' || preg_match('/[\s#"\']/', $value)) {
                $value = '"' . str_replace('"', '\"', $value) . '"';
            }
            $out .= $key . '=' . $value . "\n";
        }

        return file_put_contents($path, $out, LOCK_EX) !== false;
    }
}
